---
# yamllint disable rule:line-length
apiVersion: apps/v1  # versao da API do Kubernetes
kind: Deployment  # tipo do objeto a ser criado
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
        - name: giropops-senhas
          image: reysonbarros/giropops-senhas:1.0
          env:
            - name: REDIS_HOST
              value: "redis-0.redis.default.svc.cluster.local"
            - name: REDIS_PASSWORD
              value: "123456789@"
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 0.5
              memory: 128Mi
            limits:
              cpu: 0.8
              memory: 256Mi
          livenessProbe:  # Verificação de integridade
            exec:  # Comando executado dentro do container
              command:  # Onde iremos definir qual comando iremos executar
                - curl
                - -f
                - http://localhost:5000/
            initialDelaySeconds: 10  # Tempo aguardado antes da 1ª execução
            periodSeconds: 10  # Intervalo que a probe será executada novamente
            timeoutSeconds: 5  # Tempo para considerar que a probe falhou
            successThreshold: 1  # Qtd OK da probe -> container READY
            failureThreshold: 3  # Qtd FAIL da probe -> container NOT READY
          readinessProbe:  #  Verificação para receber tráfego(requests)
            httpGet:  # Execução de um teste HTTP
              path: /  # O caminho que iremos testar
              port: 5000  # A porta que iremos testar
            initialDelaySeconds: 10  # Tempo aguardado antes da 1ª execução
            periodSeconds: 10  # Intervalo que a probe será executada novamente
            timeoutSeconds: 5  # Tempo para considerar que a probe falhou
            successThreshold: 1  # Qtd OK da probe -> container READY
            failureThreshold: 3  # Qtd FAIL da probe -> container NOT READY
          securityContext:
            readOnlyRootFilesystem: true
      affinity:
        podAntiAffinity:  # Evita pods(same label) rodar no mesmo node(topologia)
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:  # label do pod
                matchExpressions:
                  - key: "app"  # nome da label do pod
                    operator: In
                    values:  # valores da label do pod a serem buscados
                      - giropops-senhas
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsNonRoot: true
