apiVersion: monitoring.coreos.com/v1 # versão da API
kind: ServiceMonitor # tipo de recurso, no caso, um ServiceMonitor do Prometheus Operator
metadata: # metadados do recurso
  name: giropops-senhas-servicemonitor # nome do recurso
  labels: # labels do recurso
    app: giropops-senhas
spec: # especificação do recurso
  namespaceSelector:
    matchNames:
    - dev
  selector: # seletor para identificar os pods que serão monitorados
    matchLabels: # labels que identificam os pods que serão monitorados
      app: giropops-senhas
  endpoints: # endpoints que serão monitorados
    - interval: 10s # intervalo de tempo entre as requisições
      path: /metrics # caminho para a requisição
      targetPort: 5000
