apiVersion: apps/v1 # versao da API do Kubernetes
kind: Deployment # tipo do objeto a ser criado
metadata: 
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - name: giropops-senhas
        image: reysonbarros/giropops-senhas:1.0
        env:
        - name: REDIS_HOST
          value: "redis-0.redis.default.svc.cluster.local"
        - name: REDIS_PASSWORD
          value: "123456789@"  
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 0.5      
            memory: 128Mi
          limits:   
            cpu: 0.8
            memory: 256Mi

