apiVersion: apps/v1 # versao da API do Kubernetes
kind: Deployment # tipo do objeto a ser criado
metadata: 
  name: redis-deployment
  labels:
    app: redis-deployment
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
      - name: redis
        image: cgr.dev/chainguard/redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 0.5      
            memory: 128Mi
          limits:   
            cpu: 0.8
            memory: 256Mi

