name: CI - Continuous Integration

on:
  push:
    branches:
      - "main"
      - "development"
      - "feature/cicd"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout do repositório
        uses: actions/checkout@v4
      -
        name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Configurando o Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build e push do giropops-senhas
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-senhas:1.0
      -
        name: Build e push do giropops-redis
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.redis
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-redis:7.2.3
  
  create-cluster:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout do repositório
        uses: actions/checkout@v4      
      - 
        name: Criando o cluster
        uses: helm/kind-action@v1.8.0
        with:
          version: "v0.20.0"
          config: "${{ github.workspace }}/k8s/cluster.yaml"
          node_image: "kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72"
          cluster_name: "giropops"
          kubectl_version: "v1.28.2"                    
      - 
        name: Verificando informações do cluster
        run: |
          kubectl cluster-info
          kubectl get nodes -o wide
          kubectl describe nodes
          