name: CI - Continuous Integration

on:
  push:
    branches:
      - "main"
      - "development"
      - "feature/cicd"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push giropops-senhas
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-app.yaml
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-senhas:1.0
      -
        name: Build and push giropops-redis
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-redis.yaml
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-redis:7.2.3